const data = [{weekday : "Sun" , 
date : "1" , 
formatted_date : "12/01" , 
title : "Tis a Gift" , 
type : "TV" , 
synopsis : "It's Christmas at Shining Time Station. Stacy Jones is busy helping passengers, Schemer tries to win the role of Santa's helper for the Indian Valley Gala Holiday Pageant, Mr. Conductor tells the kids a story about Thomas the Tank Engine and his friends and helps them deal with a bratty kid, while a kind old passenger, Mr. Nicholas, arrives and brightens the holiday for everybody." , 
imdb : "https://www.imdb.com/title/tt0308884" , 
img : "https://m.media-amazon.com/images/M/MV5BNDY1MDUyMzQtYTg2My00YzU5LWE4NGQtNjk5MWNlMTY0OGZmXkEyXkFqcGdeQXVyMTQ3Njg3MQ@@._V1_SY1000_CR0,0,557,1000_AL_.jpg" , 
img_pos_y : "top" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "33202" , 
runtime : "57" , 
 tv_info : {
  series : "Shining Time Station", 
  season : "2", 
  episode : "0", 
},
links : ['https://www.youtube.com/watch?v=_kURfgIfLoc']
},{weekday : "Mon" , 
date : "2" , 
formatted_date : "12/02" , 
title : "Jingle all the Way" , 
type : "MOVIE" , 
synopsis : "A father vows to get his son a Turbo Man action figure for Christmas. However, every store is sold out of them, and he must travel all over town and compete with everybody else in order to find one." , 
imdb : "https://www.imdb.com/title/tt0116705/" , 
img : "https://m.media-amazon.com/images/M/MV5BMmJlYzViNzctMjQ1Ni00ZWQ4LThkN2YtMzI2ZGU5Nzk0NTAyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY999_CR0,0,656,999_AL_.jpg" , 
img_pos_y : "top" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "35391" , 
runtime : "90" , 
links : ['https://play.hbogo.com/feature/urn:hbo:feature:GXSyb8gcArk6olAEAAAZV']
},{weekday : "Tue" , 
date : "3" , 
formatted_date : "12/03" , 
title : "Happy Christmas" , 
type : "MOVIE" , 
synopsis : "After a break up, Jenny moves in with writer Kelly, her filmmaker husband, and their child. Despite a rocky start, Jenny's influence helps Kelly realize that an evolution in her life, career and relationship is necessary for her happiness." , 
imdb : "https://www.imdb.com/title/tt2955096/" , 
img : "https://m.media-amazon.com/images/M/MV5BMTQ4MTY5NDAwM15BMl5BanBnXkFtZTgwNTUwOTEwMjE@._V1_SY1000_CR0,0,676,1000_AL_.jpg" , 
img_pos_y : "top" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "41816" , 
runtime : "82" , 
links : ['https://www.sonycrackle.com/watch/3438']
},{weekday : "Wed" , 
date : "4" , 
formatted_date : "12/04" , 
title : "A Christmas Carol" , 
type : "TV" , 
synopsis : "To help a luxury spaceship with hundreds of innocents land safely, the Doctor takes miser Kazran Sardick on a tour of his past, present and future" , 
imdb : "https://www.imdb.com/title/tt1672218/" , 
img : "https://m.media-amazon.com/images/M/MV5BMTg1MDI1MDEyMl5BMl5BanBnXkFtZTcwNzcwNTMyNA@@._V1_SY1000_CR0,0,1335,1000_AL_.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "TRUE" , 
release_date : "40537" , 
runtime : "62" , 
 tv_info : {
  series : "Doctor Who", 
  season : "6", 
  episode : "0", 
},
links : ['https://www.amazon.com/gp/video/detail/B004GEYL9M/']
},{weekday : "Thu" , 
date : "5" , 
formatted_date : "12/05" , 
title : "An Echolls Family Christmas" , 
type : "TV" , 
synopsis : "A holiday poker game at Logan's house gets nasty when Weevil's winnings disappear, leaving Veronica to determine the guilty party before Weevil finds his own way of getting the money back. Meanwhile, Keith helps Lynn Echolls find out who is sending threatening messages to her husband, Aaron, before their big Christmas party." , 
imdb : "https://www.imdb.com/title/tt0739514/" , 
img : "https://vignette.wikia.nocookie.net/veronicamars/images/e/e0/An_Echolls_Family_Christmas.png/revision/latest?cb=20120819225902" , 
img_pos_y : "" , 
img_pos_x : "left" , 
full_width : "TRUE" , 
release_date : "38335" , 
runtime : "42" , 
 tv_info : {
  series : "Veronica Mars", 
  season : "1", 
  episode : "10", 
},
links : ['https://www.hulu.com/watch/9ea32dfe-c7e5-4f5a-8523-c4a5c8a8145d']
},{weekday : "Fri" , 
date : "6" , 
formatted_date : "12/06" , 
title : "Black Santa/ White Christmas" , 
type : "TV" , 
synopsis : "Certain that his annual office Christmas party needs a black Santa, Dre goes out of his way to fill the red suit, even though the head of HR already got the job. Meanwhile, Bow doesn't feel like competing with Ruby over who cooks the big holiday dinner." , 
imdb : "https://www.imdb.com/title/tt3737494/" , 
img : "https://cdn1.edgedatg.com/aws/v2/abc/Blackish/episode/371589/0f0d74179dcb039c1771b31494c44ea7/320x180-Q100_0f0d74179dcb039c1771b31494c44ea7.jpg" , 
img_pos_y : "" , 
img_pos_x : "right" , 
full_width : "TRUE" , 
release_date : "41983" , 
runtime : "22" , 
 tv_info : {
  series : "Black-ish", 
  season : "1", 
  episode : "10", 
},
links : ['https://www.hulu.com/watch/aa962206-aeab-42c3-acbc-a3ca39bc6db3']
},{weekday : "Sat" , 
date : "7" , 
formatted_date : "12/07" , 
title : "Klaus" , 
type : "MOVIE" , 
synopsis : "A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions." , 
imdb : "https://www.imdb.com/title/tt4729430/" , 
img : "https://m.media-amazon.com/images/M/MV5BMWYwOThjM2ItZGYxNy00NTQwLWFlZWEtM2MzM2Q5MmY3NDU5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,675,1000_AL_.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "43777" , 
runtime : "96" , 
links : ['https://www.netflix.com/watch/80183187']
},{weekday : "Sun" , 
date : "8" , 
formatted_date : "12/08" , 
title : "The Knight Before Christmas" , 
type : "MOVIE" , 
synopsis : "A medieval English knight is magically transported to the present day where he falls for a high school science teacher who is disillusioned by love." , 
imdb : "https://www.imdb.com/title/tt10060094/" , 
img : "https://m.media-amazon.com/images/M/MV5BYzkyZjMyOTAtYzAwZS00NWFiLTkyOWYtYzBlN2E5YTBkMGRmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,675,1000_AL_.jpg" , 
img_pos_y : "bottom" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "43790" , 
runtime : "92" , 
links : ['https://www.netflix.com/watch/81026188']
},{weekday : "Mon" , 
date : "9" , 
formatted_date : "12/09" , 
title : "Christmas Eve on Sesame Street" , 
type : "TV" , 
synopsis : "Big Bird worries when Oscar tells him that if Santa Claus can't fit down the chimney on Christmas Eve, nobody would get presents." , 
imdb : "https://www.imdb.com/title/tt0331217/" , 
img : "https://m.media-amazon.com/images/M/MV5BNGYxYjIxNmQtM2Y0My00ODk3LThmODgtODQ3OWNiYmRjYWEyXkEyXkFqcGdeQXVyODUyMjAzMDc@._V1_.jpg" , 
img_pos_y : "top" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "28827" , 
runtime : "60" , 
 tv_info : {
  series : "Sesame Street", 
  season : "10", 
  episode : "17", 
},
links : ['https://www.dailymotion.com/video/x2a3m2x']
},{weekday : "Tue" , 
date : "10" , 
formatted_date : "12/10" , 
title : "Abed's Uncontrollable Christmas" , 
type : "TV" , 
synopsis : "When Abed wakes up to discover that everything is in stop motion animation, Professor Duncan and the study group help him try to discover the true meaning of Christmas." , 
imdb : "https://www.imdb.com/title/tt1640854/" , 
img : "https://m.media-amazon.com/images/M/MV5BMTM4MzcwMzc0Nl5BMl5BanBnXkFtZTcwMjc5MjgxNA@@._V1_.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "40521" , 
runtime : "21" , 
 tv_info : {
  series : "Community", 
  season : "2", 
  episode : "11", 
},
links : ['https://www.hulu.com/watch/e99789e7-d22d-4c39-8a69-4fe531aeb25b']
},{weekday : "Wed" , 
date : "11" , 
formatted_date : "12/11" , 
title : "Christmas Eve" , 
type : "TV" , 
synopsis : "Trying to prove how \"wild\" she can be, Amy turns a boring Christmas Eve at Cloud 9 into a holiday adventure. Meanwhile, Jonah and Garrett's roommate issues boil over. Glenn tries to prove to Mateo that Christmas is more than just \"fine.\"" , 
imdb : "https://www.imdb.com/title/tt7322058/" , 
img : "https://m.media-amazon.com/images/M/MV5BNDI0MzZmYTAtMGNhZS00ZmY3LTgzYmQtY2MyYjU5NzNjODI5XkEyXkFqcGdeQXVyMjAwMzU2MDY@._V1_.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "TRUE" , 
release_date : "43074" , 
runtime : "21" , 
 tv_info : {
  series : "Superstore", 
  season : "3", 
  episode : "7", 
},
links : ['https://www.hulu.com/watch/0e8d7d0a-1ac0-45ca-adc0-ca0a55647856']
},{weekday : "Thu" , 
date : "12" , 
formatted_date : "12/12" , 
title : "The One with the Holiday Armadillo" , 
type : "TV" , 
synopsis : "Ross wants to introduce Ben to Hanukkah. In order to entice Rachel to move back into their refurbished apartment, Phoebe must drive a wedge between Rachel and current roomie Joey." , 
imdb : "https://www.imdb.com/title/tt0583613/" , 
img : "https://m.media-amazon.com/images/M/MV5BMTgyNDIzODc0MV5BMl5BanBnXkFtZTgwOTE3NDU0MDE@._V1_SY1000_CR0,0,716,1000_AL_.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "36874" , 
runtime : "22" , 
 tv_info : {
  series : "Friends", 
  season : "7", 
  episode : "10", 
},
links : ['https://www.netflix.com/watch/70274152']
},{weekday : "Fri" , 
date : "13" , 
formatted_date : "12/13" , 
title : "Nightmare Before Christmas" , 
type : "MOVIE" , 
synopsis : "Jack Skellington, king of Halloween Town, discovers Christmas Town, but his attempts to bring Christmas to his home causes confusion." , 
imdb : "https://www.imdb.com/title/tt0107688" , 
img : "https://m.media-amazon.com/images/M/MV5BNWE4OTNiM2ItMjY4Ni00ZTViLWFiZmEtZGEyNGY2ZmNlMzIyXkEyXkFqcGdeQXVyMDU5NDcxNw@@._V1_SY1000_CR0,0,666,1000_AL_.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "34271" , 
runtime : "76" , 
links : ['https://www.disneyplus.com/video/5c765c2c-cf09-44ca-b5f1-d2697f3da620']
},{weekday : "Sat" , 
date : "14" , 
formatted_date : "12/14" , 
title : "Night of the Meek" , 
type : "TV" , 
synopsis : "After a derelict Santa Claus is fired on Christmas Eve, he finds a mysterious bag that gives out presents. With this bag he sets out to fulfill his one wish - to see the less fortunate inherit the bounties of Christmas." , 
imdb : "https://www.imdb.com/title/tt0734666" , 
img : "https://m.media-amazon.com/images/M/MV5BMjMwNTE3Njg4N15BMl5BanBnXkFtZTgwNTEzOTEyMjE@._V1_.jpg" , 
img_pos_y : "" , 
img_pos_x : "right" , 
full_width : "TRUE" , 
release_date : "22273" , 
runtime : "25" , 
 tv_info : {
  series : "The Twilight Zone", 
  season : "2", 
  episode : "11", 
},
links : ['https://www.netflix.com/watch/70174051']
},{weekday : "Sun" , 
date : "15" , 
formatted_date : "12/15" , 
title : "My Own Personal Jesus" , 
type : "TV" , 
synopsis : "It is Christmas time and no one except Turk feels like celebrating. Cox gets J.D. to video the birth of a friends baby, and once again, nothing seems to go right!" , 
imdb : "https://www.imdb.com/title/tt0696619" , 
img : "https://m.media-amazon.com/images/M/MV5BMjEwODkxNDEzNl5BMl5BanBnXkFtZTgwNzQxNjczMjE@._V1_.jpg" , 
img_pos_y : "" , 
img_pos_x : "left" , 
full_width : "TRUE" , 
release_date : "37236" , 
runtime : "24" , 
 tv_info : {
  series : "Scrubs", 
  season : "1", 
  episode : "11", 
},
links : ['https://www.hulu.com/watch/878bcd7e-83ab-4cff-a4b8-bd72230566c6']
},{weekday : "Mon" , 
date : "16" , 
formatted_date : "12/16" , 
title : "National Lampoon's Christmas Vacation" , 
type : "MOVIE" , 
synopsis : "The Griswold family's plans for a big family Christmas predictably turn into a big disaster." , 
imdb : "https://www.imdb.com/title/tt0097958/" , 
img : "https://m.media-amazon.com/images/M/MV5BMGZkMWQ2MzMtYTkxYS00OThmLWI0ZTQtNmY0ZTkyY2E4MjliXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg" , 
img_pos_y : "bottom" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "32843" , 
runtime : "97" , 
links : ['']
},{weekday : "Tue" , 
date : "17" , 
formatted_date : "12/17" , 
title : "Die Hard" , 
type : "MOVIE" , 
synopsis : "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles. " , 
imdb : "https://www.imdb.com/title/tt0095016/" , 
img : "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,666,1000_AL_.jpg" , 
img_pos_y : "bottom" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "32344" , 
runtime : "132" , 
links : ['https://www.sonycrackle.com/watch/3805']
},{weekday : "Wed" , 
date : "18" , 
formatted_date : "12/18" , 
title : "In Excelsis Deo" , 
type : "TV" , 
synopsis : "When a homeless veteran dies on the National Mall and his body remains uncollected for hours, Toby becomes fixated on getting him a proper burial." , 
imdb : "https://www.imdb.com/title/tt0745635/" , 
img : "https://m.media-amazon.com/images/M/MV5BMjE5MjAzNjI3MV5BMl5BanBnXkFtZTgwODgwMjY1MjE@._V1_.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "TRUE" , 
release_date : "36509" , 
runtime : "45" , 
 tv_info : {
  series : "The West Wing", 
  season : "1", 
  episode : "10", 
},
links : ['https://www.netflix.com/watch/70262092']
},{weekday : "Thu" , 
date : "19" , 
formatted_date : "12/19" , 
title : "Making It" , 
type : "TV" , 
synopsis : "The Makers celebrate the holidays with Nick and Amy. First, in the Faster Craft, they will make a wreath out of unconventional materials. In the Master Craft they will build an interactive lawn display, showcasing their favorite holiday. " , 
imdb : "https://www.imdb.com/title/tt8912212" , 
img : "https://m.media-amazon.com/images/M/MV5BMzIxOWViNjItOTAxMC00ZjdmLTkzYTMtYWU1OTlmYmIwYmJjXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "43804" , 
runtime : "45" , 
 tv_info : {
  series : "Wreathy Street", 
  season : "2", 
  episode : "4", 
},
links : ['https://www.hulu.com/series/making-it-3555d650-dde9-443b-84c7-0132cdbe03d0']
},{weekday : "Fri" , 
date : "20" , 
formatted_date : "12/20" , 
title : "Episode Title TBD" , 
type : "PODCAST" , 
synopsis : "Off Book is an improvised musical podcast. For the last two years, they've recorded new, original holiday themed episodes with Paul F Thompkins and Nicole Parker." , 
imdb : "_" , 
img : "https://www.earwolf.com/wp-content/uploads/2017/07/EAR_COVER_OffBook_3000x3000_F.jpg" , 
img_pos_y : "" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "43815" , 
runtime : "65" , 
links : ['https://podcasts.apple.com/us/podcast/off-book-the-improvised-musical/id1260742439?mt=2']
},{weekday : "Sat" , 
date : "21" , 
formatted_date : "12/21" , 
title : "Marionettes" , 
type : "TV" , 
synopsis : "After Elizabeth makes a tone-deaf speech at a Jaguar factory, she and the monarchy come under public attack by an outspoken lord." , 
imdb : "https://www.imdb.com/title/tt6718340" , 
img : "https://m.media-amazon.com/images/M/MV5BMzdmYjI4ODUtZDIzNC00ZDE3LWI1MjYtMzZiNDU1NWE5MGY4XkEyXkFqcGdeQXVyNzgxNDM4MA@@._V1_.jpg" , 
img_pos_y : "" , 
img_pos_x : "right" , 
full_width : "TRUE" , 
release_date : "43077" , 
runtime : "61" , 
 tv_info : {
  series : "The Crown", 
  season : "2", 
  episode : "5", 
},
links : ['https://www.netflix.com/watch/80149009']
},{weekday : "Sun" , 
date : "22" , 
formatted_date : "12/22" , 
title : "Love Actually" , 
type : "MOVIE" , 
synopsis : "Follows the lives of eight very different couples in dealing with their love lives in various loosely interrelated tales all set during a frantic month before Christmas in London, England." , 
imdb : "https://www.imdb.com/title/tt0314331" , 
img : "https://m.media-amazon.com/images/M/MV5BMTY4NjQ5NDc0Nl5BMl5BanBnXkFtZTYwNjk5NDM3._V1_.jpg" , 
img_pos_y : "bottom" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "37939" , 
runtime : "135" , 
links : ['https://play.hbogo.com/feature/urn:hbo:feature:GXToZygqeDI-dUQEAAGSV']
},{weekday : "Mon" , 
date : "23" , 
formatted_date : "12/23" , 
title : "Charlie Brown Christmas" , 
type : "MOVIE" , 
synopsis : "Depressed at the commercialism he sees around him, Charlie Brown tries to find a deeper meaning to Christmas." , 
imdb : "https://www.imdb.com/title/tt0059026/" , 
img : "https://m.media-amazon.com/images/M/MV5BMTQ1NDQxNTcxN15BMl5BanBnXkFtZTgwNzY1Njc1MzE@._V1_.jpg" , 
img_pos_y : "top" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "24085" , 
runtime : "25" , 
links : ['https://www.dailymotion.com/video/x7g87qh']
},{weekday : "Tue" , 
date : "24" , 
formatted_date : "12/24" , 
title : "Spot's Magical Christmas" , 
type : "MOVIE" , 
synopsis : "Spot goes on a quest to find Santa's missing sleigh." , 
imdb : "https://www.imdb.com/title/tt1764607/" , 
img : "https://m.media-amazon.com/images/M/MV5BMjI1MzE4NzI0MV5BMl5BanBnXkFtZTcwODMwOTc0NA@@._V1_.jpg" , 
img_pos_y : "top" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "35053" , 
runtime : "30" , 
links : ['https://archive.org/details/SpotsMagicalChristmas978522VHS']
},{weekday : "Wed" , 
date : "25" , 
formatted_date : "12/25" , 
title : "Rugrats Hannukah" , 
type : "TV" , 
synopsis : "During Chanukah, the babies try to help Boris deal with a childhood rival, he is appearing with in a synagogue pageant. Angelica tries to watch a Christmas special." , 
imdb : "https://www.imdb.com/title/tt1159155/" , 
img : "https://m.media-amazon.com/images/M/MV5BMTM5OTIyNjU1Ml5BMl5BanBnXkFtZTcwOTExNTMyMQ@@._V1_.jpg" , 
img_pos_y : "top" , 
img_pos_x : "" , 
full_width : "" , 
release_date : "35405" , 
runtime : "24" , 
 tv_info : {
  series : "Rugrats", 
  season : "4", 
  episode : "1", 
},
links : ['https://www.hulu.com/watch/b304e316-c153-4eb0-94a9-40b7b3655fa5']
}];